import { TopologyResponse, RCAResult, IncidentSummary, AgentWSMessage } from "./types";

export const MOCK_TOPOLOGY: TopologyResponse = {
  nodes: [
    // Gateways
    { id: "api-gateway", name: "api-gateway", type: "gateway", tier: "gateway", anomaly_score: 0.72, status: "degraded", metrics: { cpu_percent: 68.2, memory_percent: 54.1, latency_p95: 412.0, error_rate: 6.4, requests_per_sec: 2400 } },
    { id: "ingress-lb", name: "ingress-lb", type: "gateway", tier: "gateway", anomaly_score: 0.65, status: "degraded", metrics: { cpu_percent: 52.0, memory_percent: 48.0, latency_p95: 395.0, error_rate: 5.8, requests_per_sec: 2900 } },
    { id: "mobile-gateway", name: "mobile-gateway", type: "gateway", tier: "gateway", anomaly_score: 0.45, status: "healthy", metrics: { cpu_percent: 34.0, memory_percent: 42.0, latency_p95: 85.0, error_rate: 0.8, requests_per_sec: 1100 } },

    // Frontend
    { id: "web-frontend", name: "web-frontend", type: "service", tier: "frontend", anomaly_score: 0.78, status: "degraded", metrics: { cpu_percent: 74.5, memory_percent: 62.0, latency_p95: 580.0, error_rate: 8.2, requests_per_sec: 1800 } },
    { id: "mobile-frontend", name: "mobile-frontend", type: "service", tier: "frontend", anomaly_score: 0.38, status: "healthy", metrics: { cpu_percent: 29.0, memory_percent: 39.0, latency_p95: 45.0, error_rate: 0.2, requests_per_sec: 950 } },
    { id: "admin-portal", name: "admin-portal", type: "service", tier: "frontend", anomaly_score: 0.12, status: "healthy", metrics: { cpu_percent: 18.0, memory_percent: 31.0, latency_p95: 22.0, error_rate: 0.0, requests_per_sec: 120 } },

    // Core Backends
    { id: "order-orchestrator", name: "order-orchestrator", type: "service", tier: "backend", anomaly_score: 0.99, status: "critical", metrics: { cpu_percent: 98.6, memory_percent: 92.4, latency_p95: 1420.0, error_rate: 28.5, requests_per_sec: 420 } },
    { id: "order-fulfillment", name: "order-fulfillment", type: "service", tier: "backend", anomaly_score: 0.84, status: "critical", metrics: { cpu_percent: 88.0, memory_percent: 78.0, latency_p95: 980.0, error_rate: 18.4, requests_per_sec: 380 } },
    { id: "cart-service", name: "cart-service", type: "service", tier: "backend", anomaly_score: 0.71, status: "degraded", metrics: { cpu_percent: 64.0, memory_percent: 58.0, latency_p95: 390.0, error_rate: 4.8, requests_per_sec: 850 } },
    { id: "payment-gateway-proxy", name: "payment-gateway-proxy", type: "service", tier: "backend", anomaly_score: 0.58, status: "degraded", metrics: { cpu_percent: 55.0, memory_percent: 49.0, latency_p95: 310.0, error_rate: 3.2, requests_per_sec: 410 } },
    { id: "payment-processor", name: "payment-processor", type: "service", tier: "backend", anomaly_score: 0.22, status: "healthy", metrics: { cpu_percent: 38.0, memory_percent: 44.0, latency_p95: 65.0, error_rate: 0.1, requests_per_sec: 390 } },
    { id: "inventory-manager", name: "inventory-manager", type: "service", tier: "backend", anomaly_score: 0.62, status: "degraded", metrics: { cpu_percent: 61.0, memory_percent: 52.0, latency_p95: 340.0, error_rate: 3.8, requests_per_sec: 530 } },
    { id: "warehouse-dispatcher", name: "warehouse-dispatcher", type: "service", tier: "backend", anomaly_score: 0.15, status: "healthy", metrics: { cpu_percent: 24.0, memory_percent: 35.0, latency_p95: 28.0, error_rate: 0.0, requests_per_sec: 140 } },
    { id: "auth-service", name: "auth-service", type: "service", tier: "backend", anomaly_score: 0.18, status: "healthy", metrics: { cpu_percent: 31.0, memory_percent: 40.0, latency_p95: 18.0, error_rate: 0.05, requests_per_sec: 3200 } },
    { id: "user-profile-service", name: "user-profile-service", type: "service", tier: "backend", anomaly_score: 0.14, status: "healthy", metrics: { cpu_percent: 26.0, memory_percent: 37.0, latency_p95: 24.0, error_rate: 0.0, requests_per_sec: 820 } },
    { id: "catalog-service", name: "catalog-service", type: "service", tier: "backend", anomaly_score: 0.19, status: "healthy", metrics: { cpu_percent: 28.0, memory_percent: 41.0, latency_p95: 21.0, error_rate: 0.0, requests_per_sec: 1400 } },
    { id: "search-service", name: "search-service", type: "service", tier: "backend", anomaly_score: 0.16, status: "healthy", metrics: { cpu_percent: 33.0, memory_percent: 46.0, latency_p95: 35.0, error_rate: 0.0, requests_per_sec: 1100 } },
    { id: "recommendation-engine", name: "recommendation-engine", type: "service", tier: "backend", anomaly_score: 0.11, status: "healthy", metrics: { cpu_percent: 42.0, memory_percent: 58.0, latency_p95: 54.0, error_rate: 0.0, requests_per_sec: 420 } },
    { id: "notification-dispatcher", name: "notification-dispatcher", type: "service", tier: "backend", anomaly_score: 0.08, status: "healthy", metrics: { cpu_percent: 19.0, memory_percent: 28.0, latency_p95: 15.0, error_rate: 0.0, requests_per_sec: 640 } },

    // Data Tier
    { id: "postgres-primary", name: "postgres-primary", type: "database", tier: "data", anomaly_score: 0.42, status: "healthy", metrics: { cpu_percent: 58.0, memory_percent: 69.0, latency_p95: 45.0, error_rate: 0.4, requests_per_sec: 1800 } },
    { id: "postgres-replica", name: "postgres-replica", type: "database", tier: "data", anomaly_score: 0.15, status: "healthy", metrics: { cpu_percent: 32.0, memory_percent: 54.0, latency_p95: 18.0, error_rate: 0.0, requests_per_sec: 1200 } },
    { id: "mongodb-orders", name: "mongodb-orders", type: "database", tier: "data", anomaly_score: 0.48, status: "healthy", metrics: { cpu_percent: 62.0, memory_percent: 71.0, latency_p95: 52.0, error_rate: 0.6, requests_per_sec: 900 } },
    { id: "redis-cache-master", name: "redis-cache-master", type: "cache", tier: "data", anomaly_score: 0.20, status: "healthy", metrics: { cpu_percent: 24.0, memory_percent: 48.0, latency_p95: 3.2, error_rate: 0.0, requests_per_sec: 4500 } },
    { id: "elasticsearch-cluster", name: "elasticsearch-cluster", type: "database", tier: "data", anomaly_score: 0.12, status: "healthy", metrics: { cpu_percent: 35.0, memory_percent: 60.0, latency_p95: 14.0, error_rate: 0.0, requests_per_sec: 780 } },

    // Messaging
    { id: "kafka-broker-1", name: "kafka-broker-1", type: "queue", tier: "messaging", anomaly_score: 0.35, status: "healthy", metrics: { cpu_percent: 41.0, memory_percent: 55.0, latency_p95: 12.0, error_rate: 0.1, requests_per_sec: 3200 } },
    { id: "rabbitmq-orders", name: "rabbitmq-orders", type: "queue", tier: "messaging", anomaly_score: 0.44, status: "healthy", metrics: { cpu_percent: 49.0, memory_percent: 63.0, latency_p95: 16.0, error_rate: 0.2, requests_per_sec: 1600 } },
  ],
  edges: [
    { id: "e1", source: "ingress-lb", target: "api-gateway", type: "CALLS", weight: 1.0, latency_ms: 4.2 },
    { id: "e2", source: "api-gateway", target: "web-frontend", type: "CALLS", weight: 0.9, latency_ms: 12.0 },
    { id: "e3", source: "api-gateway", target: "mobile-frontend", type: "CALLS", weight: 0.7, latency_ms: 8.5 },
    { id: "e4", source: "web-frontend", target: "auth-service", type: "CALLS", weight: 0.9, latency_ms: 15.0 },
    { id: "e5", source: "web-frontend", target: "cart-service", type: "CALLS", weight: 0.85, latency_ms: 42.0 },
    { id: "e6", source: "cart-service", target: "order-orchestrator", type: "CALLS", weight: 0.95, latency_ms: 840.0 },
    { id: "e7", source: "web-frontend", target: "order-orchestrator", type: "CALLS", weight: 0.9, latency_ms: 920.0 },
    { id: "e8", source: "order-orchestrator", target: "order-fulfillment", type: "CALLS", weight: 0.95, latency_ms: 320.0 },
    { id: "e9", source: "order-orchestrator", target: "payment-gateway-proxy", type: "CALLS", weight: 0.85, latency_ms: 210.0 },
    { id: "e10", source: "payment-gateway-proxy", target: "payment-processor", type: "CALLS", weight: 0.9, latency_ms: 45.0 },
    { id: "e11", source: "order-orchestrator", target: "inventory-manager", type: "CALLS", weight: 0.8, latency_ms: 180.0 },
    { id: "e12", source: "inventory-manager", target: "warehouse-dispatcher", type: "CALLS", weight: 0.7, latency_ms: 22.0 },
    { id: "e13", source: "order-orchestrator", target: "mongodb-orders", type: "DEPENDS_ON", weight: 0.9, latency_ms: 34.0 },
    { id: "e14", source: "order-orchestrator", target: "rabbitmq-orders", type: "WRITES_TO", weight: 0.8, latency_ms: 12.0 },
    { id: "e15", source: "cart-service", target: "redis-cache-master", type: "CALLS", weight: 0.9, latency_ms: 3.5 },
    { id: "e16", source: "auth-service", target: "postgres-primary", type: "DEPENDS_ON", weight: 0.95, latency_ms: 8.0 },
    { id: "e17", source: "postgres-primary", target: "postgres-replica", type: "CALLS", weight: 0.9, latency_ms: 5.0 },
    { id: "e18", source: "web-frontend", target: "catalog-service", type: "CALLS", weight: 0.8, latency_ms: 18.0 },
    { id: "e19", source: "catalog-service", target: "search-service", type: "CALLS", weight: 0.75, latency_ms: 25.0 },
    { id: "e20", source: "search-service", target: "elasticsearch-cluster", type: "DEPENDS_ON", weight: 0.9, latency_ms: 12.0 },
    { id: "e21", source: "web-frontend", target: "recommendation-engine", type: "CALLS", weight: 0.6, latency_ms: 35.0 },
    { id: "e22", source: "order-fulfillment", target: "notification-dispatcher", type: "CALLS", weight: 0.7, latency_ms: 16.0 },
    { id: "e23", source: "notification-dispatcher", target: "kafka-broker-1", type: "WRITES_TO", weight: 0.85, latency_ms: 9.0 },
  ],
  fault_gradients: {
    "order-orchestrator": 1.0,
    "order-fulfillment": 0.84,
    "web-frontend": 0.78,
    "api-gateway": 0.72,
    "cart-service": 0.71,
    "ingress-lb": 0.65,
    "inventory-manager": 0.62,
    "payment-gateway-proxy": 0.58,
    "mongodb-orders": 0.48,
    "rabbitmq-orders": 0.44,
    "postgres-primary": 0.42,
    "payment-processor": 0.22,
    "redis-cache-master": 0.20,
    "catalog-service": 0.19,
    "auth-service": 0.18,
    "search-service": 0.16,
    "postgres-replica": 0.15,
    "warehouse-dispatcher": 0.15,
    "user-profile-service": 0.14,
    "elasticsearch-cluster": 0.12,
    "admin-portal": 0.12,
    "recommendation-engine": 0.11,
    "notification-dispatcher": 0.08,
    "kafka-broker-1": 0.35,
    "mobile-gateway": 0.45,
    "mobile-frontend": 0.38,
  },
  metadata: {
    total_nodes: 26,
    total_edges: 23,
    fault_info: {
      root_cause_node: "order-orchestrator",
      fault_type: "cpu_saturation",
      injected_score: 0.99,
      affected_node_count: 8,
    },
  },
};

export const MOCK_RCA_RESULT: RCAResult = {
  rca_id: "rca-20260924-001",
  incident_id: "INC-9821",
  root_cause_node: "order-orchestrator",
  confidence: 0.946,
  evidence: [
    "CPU utilization sustained above 98.4% for 18 consecutive minutes",
    "JVM garbage collection STW pauses elevated from 12ms baseline to 4,200ms",
    "Downstream dependency calls to mongodb-orders experiencing timeout cascades (SLA breach > 3000ms)",
    "Distributed trace analysis confirms 89% of failing spans originate at order-orchestrator::/process_checkout",
    "Temporal knowledge graph shows upstream anomaly propagation to cart-service and web-frontend with gradient attenuation (decay 0.65)",
    "Adversarial Verifier validated hypothesis against counterfactual: simulated DB recovery does not resolve checkout stalls",
  ],
  agent_trace: [
    {
      agent: "navigator",
      action: "Graph Subgraph Extraction & Gradient Calculation",
      timestamp: "00:01:12",
      details: "Computed anomaly propagation vectors over 65 microservice nodes. Filtered candidate subgraph down to 4 high-gradient nodes: [order-orchestrator, cart-service, order-fulfillment, payment-gateway-proxy].",
      metadata: { candidate_count: 4, traversal_depth: 3 },
    },
    {
      agent: "diagnoser",
      action: "Multimodal Telemetry Semantic Reasoning",
      timestamp: "00:01:28",
      details: "Correlated CPU time-series metrics, OpenTelemetry spans, and thread dump logs. Formulated Root Cause Hypothesis: Synchronous lock contention and thread starvation in OrderOrchestrator worker pool during inventory reserve check.",
      metadata: { confidence_raw: 0.96, primary_evidence: "Thread starvation in WorkerPool-4" },
    },
    {
      agent: "verifier",
      action: "Adversarial Counterfactual Validation Protocol",
      timestamp: "00:01:42",
      details: "Formulated counterfactual query: 'If MongoDB latency is clamped to 10ms baseline, does the failure persist?' Simulation: YES (lock persists). Verdict: ACCEPT. Hypothesis verified as true root cause rather than downstream symptom.",
      metadata: { status: "ACCEPT", counterfactual_tests_passed: 3 },
    },
  ],
  counterfactual_results: [
    {
      hypothesis: "Root cause is upstream network bottleneck at api-gateway",
      test: "Simulate zero packet drop on ingress routes",
      status: "REJECT",
      reasoning: "Synthetic network isolation reveals order-orchestrator CPU remains pinned at 99% independently of gateway throughput.",
      p_value: 0.002,
    },
    {
      hypothesis: "Root cause is mongodb-orders write lock exhaustion",
      test: "Simulate synthetic instantaneous DB acknowledgment",
      status: "REJECT",
      reasoning: "Mocked instant DB responses fail to clear thread blockage in order-orchestrator. Root cause precedes DB call.",
      p_value: 0.008,
    },
    {
      hypothesis: "Root cause is CPU core starvation in order-orchestrator container pod",
      test: "Correlate thread dump mutex locks with cgroup throttling events",
      status: "ACCEPT",
      reasoning: "Consistent match across CFS throttle statistics (78% throttled runtime) and thread dump mutex wait chains.",
      p_value: 0.985,
    },
  ],
  remediation_suggestions: [
    "Scale order-orchestrator deployment horizontal replica count from 3 to 8 pods immediately: kubectl scale deployment order-orchestrator --replicas=8",
    "Increase CPU limit in Kubernetes pod spec: set resources.limits.cpu from 2000m to 4000m to eliminate cgroup throttling",
    "Enable circuit breaking on upstream cart-service -> order-orchestrator client with 500ms timeout to shed load during recovery",
    "Deploy hotfix patch v2.4.1 to replace synchronized block in OrderService.java:142 with non-blocking ConcurrentHashMap batch reservation",
  ],
  created_at: "2026-09-24T00:01:45Z",
  execution_duration_sec: 3.42,
};

export const MOCK_INCIDENTS: IncidentSummary[] = [
  {
    incident_id: "INC-9821",
    rca_id: "rca-20260924-001",
    title: "Checkout Latency Spike & Cascading HTTP 504 Failures",
    severity: "CRITICAL",
    detected_at: "2026-09-24 00:01:10 UTC",
    status: "VERIFIED",
    root_cause_service: "order-orchestrator",
    confidence: 0.946,
    mttr_min: 3.2,
  },
  {
    incident_id: "INC-9818",
    rca_id: "rca-20260923-014",
    title: "Payment Gateway Connection Pool Starvation",
    severity: "HIGH",
    detected_at: "2026-09-23 18:24:00 UTC",
    status: "RESOLVED",
    root_cause_service: "payment-gateway-proxy",
    confidence: 0.912,
    mttr_min: 4.8,
  },
  {
    incident_id: "INC-9815",
    rca_id: "rca-20260923-009",
    title: "Memory Leak in Cart Session Redis Adapter",
    severity: "HIGH",
    detected_at: "2026-09-23 11:45:22 UTC",
    status: "RESOLVED",
    root_cause_service: "cart-service",
    confidence: 0.887,
    mttr_min: 5.1,
  },
  {
    incident_id: "INC-9809",
    rca_id: "rca-20260922-003",
    title: "Kafka Consumer Lag & Notification Delay",
    severity: "MEDIUM",
    detected_at: "2026-09-22 09:12:15 UTC",
    status: "RESOLVED",
    root_cause_service: "notification-dispatcher",
    confidence: 0.954,
    mttr_min: 2.8,
  },
];

export const MOCK_WS_TIMELINE: AgentWSMessage[] = [
  {
    agent: "system",
    status: "running",
    data: {
      step: 1,
      title: "Incident Ingested",
      message: "Telemetry window: 30m. Constructing temporal dependency graph snapshot...",
      timestamp: "00:00:01",
    },
  },
  {
    agent: "navigator",
    status: "running",
    data: {
      step: 2,
      title: "Graph Traversal & Gradient Calculation",
      message: "Executing fault propagation gradient algorithm upstream from degraded boundary nodes...",
      traversed_nodes: ["ingress-lb", "api-gateway", "web-frontend", "cart-service", "order-orchestrator"],
      timestamp: "00:00:02",
    },
  },
  {
    agent: "navigator",
    status: "completed",
    data: {
      step: 3,
      title: "Subgraph Localized",
      message: "Candidate root causes isolated: [order-orchestrator (1.00), order-fulfillment (0.84), cart-service (0.71)]. Dispatching subgraph to Diagnoser.",
      candidate_root_causes: ["order-orchestrator", "order-fulfillment", "cart-service"],
      timestamp: "00:00:03",
    },
  },
  {
    agent: "diagnoser",
    status: "running",
    data: {
      step: 4,
      title: "Semantic Telemetry Analysis",
      message: "Correlating 1,300 time-series metric points, 60 OpenTelemetry traces, and 150 structured log lines across candidate nodes...",
      timestamp: "00:00:04",
    },
  },
  {
    agent: "diagnoser",
    status: "completed",
    data: {
      step: 5,
      title: "Root Cause Hypothesis Formulated",
      message: "Hypothesis: CPU core starvation and lock contention in order-orchestrator pod causing synchronous thread exhaustion.",
      confidence: 0.96,
      timestamp: "00:00:05",
    },
  },
  {
    agent: "verifier",
    status: "running",
    data: {
      step: 6,
      title: "Adversarial Counterfactual Testing",
      message: "Challenging hypothesis with counterfactual questions: Is order-orchestrator symptom of DB degradation or true originator?",
      counterfactual_check: {
        question: "Does bottleneck persist if downstream DB latency is neutralized?",
        verdict: "ACCEPT",
        explanation: "Counterfactual simulation demonstrates thread stall occurs independently of DB response time. True root cause confirmed.",
      },
      timestamp: "00:00:06",
    },
  },
  {
    agent: "verifier",
    status: "completed",
    data: {
      step: 7,
      title: "Verification Complete — ACCEPT",
      message: "Hypothesis passed all 3 adversarial checks. Confidence calibrated to 94.6%. Emitting final verified RCA package.",
      confidence: 0.946,
      timestamp: "00:00:07",
    },
  },
];
